version: "3"

services:
  ros2:
    image: ghcr.io/teruyamato0731/dev-humble
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      # Working
      - ../:/workspaces/slam_toolbox_test:cached
      # GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    command: sleep infinity
    working_dir: /workspaces/slam_toolbox_test
